# TRTS
train on real dataset and test on synthetic data

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
HOME_PATH = 'C:/Users/27261/Desktop/prostate/code-0126/'
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(HOME_PATH + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
# read real dataset
train_data = pd.read_csv(HOME_PATH + 'Dataset_cedric/train.csv')
categorical_columns = ["cT(MRI)","Multifocaal", "pN", "1c (0) - Perifeer (1) -  Beide (2) - Transitie (3)"]
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,eadnr (I),Age,Multifocaal,1c (0) - Perifeer (1) - Beide (2) - Transitie (3),Preoperatief PSA,Aantal zones positive percentage,Primaire Gleason,Secundaire Gleason,Grade group (highest),Target biopsie Core length (perc),...,Grootste diameter (percentage of tumor),Grootste mm aantasting (mms),Primaire,Secundaire,Grade group Grootste mm aantasting,Primaire Gleason.1,Secundaire Gleason.1,Grade Group,pN,cT(MRI)
0,74911959,60.254795,0,3,1.90,0.300000,3,4,2,20.0,...,20.0,4.0,3,4,2,3,3,1,0,1
1,72364086,66.391781,1,3,4.02,0.300000,4,3,3,8.0,...,87.0,7.0,3,3,1,3,3,1,0,1
2,72845225,69.010959,0,1,4.60,0.250000,4,4,4,17.0,...,17.0,2.0,4,4,4,4,3,3,0,4
3,65384463,41.136986,0,3,5.00,0.666667,3,4,2,46.0,...,46.0,6.0,3,4,2,3,4,2,0,1
4,83257287,74.665753,0,1,10.90,1.000000,4,5,5,100.0,...,100.0,17.0,4,5,5,4,5,5,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,77679900,68.350685,0,1,4.91,0.500000,4,5,5,30.0,...,30.0,4.0,4,4,4,4,3,3,1,4
229,70544747,73.531507,0,1,9.70,1.000000,4,3,3,31.0,...,31.0,4.0,3,4,2,3,4,2,0,4
230,88824362,65.734247,0,1,10.30,1.000000,4,3,3,83.0,...,83.0,10.0,4,3,3,4,3,3,0,4
231,61072681,60.189041,0,1,10.80,0.200000,3,3,1,30.0,...,30.0,4.5,3,3,1,3,3,1,0,4
232,89901847,69.282192,1,2,7.70,0.727273,3,4,2,93.0,...,93.0,14.0,3,4,2,3,4,2,0,5

## CTGAN

In [5]:
#read test data
test_data = pd.read_csv(HOME_PATH + 'Dataset_cedric/SYNTHETIC DATASETS/CTGAN.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,eadnr (I),Age,Multifocaal,1c (0) - Perifeer (1) - Beide (2) - Transitie (3),Preoperatief PSA,Aantal zones positive percentage,Primaire Gleason,Secundaire Gleason,Grade group (highest),Target biopsie Core length (perc),...,Grootste diameter (percentage of tumor),Grootste mm aantasting (mms),Primaire,Secundaire,Grade group Grootste mm aantasting,Primaire Gleason.1,Secundaire Gleason.1,Grade Group,pN,cT(MRI)
0,77811907,70.93,0,2,9.18,0.27,4,4,3,55.35,...,88.56,4.46,4,5,2,4,3,2,0,0
1,81053954,67.77,1,1,11.45,0.95,4,3,3,79.71,...,115.18,4.29,3,4,1,3,3,2,0,4
2,76127604,67.25,1,1,11.62,0.88,4,3,3,101.93,...,68.66,0.40,3,4,2,3,5,5,0,4
3,79619898,56.37,0,1,13.62,0.41,4,4,4,83.65,...,98.79,5.75,3,4,1,4,4,2,0,3
4,74510538,54.60,0,2,12.55,0.90,3,6,2,86.44,...,79.78,4.20,3,3,3,3,4,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,73141046,72.18,0,3,7.44,0.78,3,4,3,58.80,...,65.61,-0.52,4,5,6,3,3,3,0,4
229,85460302,75.93,1,1,14.79,0.67,3,4,3,49.97,...,95.96,-0.82,3,4,4,3,4,2,0,1
230,83156614,71.82,1,1,9.42,1.16,4,3,3,86.94,...,76.14,2.34,3,4,5,4,5,2,0,6
231,77291550,72.03,0,1,19.53,0.67,4,4,3,76.01,...,92.59,-1.70,3,3,3,4,3,3,0,0
232,73251890,71.17,0,3,15.15,0.41,3,4,3,29.25,...,53.80,1.51,4,4,3,4,3,2,0,4

In [7]:
target = 'pN'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(233, 35)
pN
0    198
1     35
dtype: int64
#####################################
Test data
(233, 35)
pN
0    182
1     51
dtype: int64

## 2. Pre-process training data

In [8]:
target = "pN"
categorical_columns = ["cT(MRI)","Multifocaal", "1c (0) - Perifeer (1) -  Beide (2) - Transitie (3)"]
numerical_columns = numerical_columns = train_data.select_dtypes(include=['int64']).columns.tolist()
categories = [np.array(range(7)), np.array(range(2)), np.array(range(4))]

data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((233, 33), (233,))

## 3. Preprocess test data

In [9]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((233, 33), (233,))

## 4. Create a dataset to save the results

In [10]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [11]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall     f1
0    RF    0.7768     0.6094  0.7768  0.683

## 5. Train and Evaluate KNeighbors Classifier

In [12]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.7811     0.6101  0.7811  0.6851

## 6. Train and evaluate Decision Tree Classifier

In [13]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.6052     0.6402  0.6052  0.6211

## 7. Train and evaluate Support Vector Machines Classifier

In [14]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM]

  model  accuracy  precision  recall      f1
0   SVM    0.5794      0.679  0.5794  0.6133

## 8. Train and evaluate Multilayer Perceptron Classifier

In [15]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.71846698
Iteration 2, loss = 0.62174230
Iteration 3, loss = 0.54967201
Iteration 4, loss = 0.49603910
Iteration 5, loss = 0.45494646
Iteration 6, loss = 0.42426190
Iteration 7, loss = 0.40286383
Iteration 8, loss = 0.38670654
Iteration 9, loss = 0.37607415
Iteration 10, loss = 0.37176484
Iteration 11, loss = 0.36325690
Iteration 12, loss = 0.35481351
Iteration 13, loss = 0.34664536
Iteration 14, loss = 0.33836099
Iteration 15, loss = 0.33092113
Iteration 16, loss = 0.32500804
Iteration 17, loss = 0.31966319
Iteration 18, loss = 0.31376518
Iteration 19, loss = 0.30823628
Iteration 20, loss = 0.30271352
Iteration 21, loss = 0.29677459
Iteration 22, loss = 0.29006417
Iteration 23, loss = 0.28465954
Iteration 24, loss = 0.27920441
Iteration 25, loss = 0.27550947
Iteration 26, loss = 0.27266383
Iteration 27, loss = 0.27026002
Iteration 28, loss = 0.26733353
Iteration 29, loss = 0.26360021
Iteration 30, loss = 0.25937418
Iteration 31, loss = 0.25503752
Iteration 32, loss = 0.25043150
Iteration 33, loss = 0.24602285
Iteration 34, loss = 0.24276625
Iteration 35, loss = 0.23966243
Iteration 36, loss = 0.23506990
Iteration 37, loss = 0.23135566
Iteration 38, loss = 0.22807665
Iteration 39, loss = 0.22569112
Iteration 40, loss = 0.22287683
Iteration 41, loss = 0.21988640
Iteration 42, loss = 0.21657298
Iteration 43, loss = 0.21400299
Iteration 44, loss = 0.21000155
Iteration 45, loss = 0.20499312
Iteration 46, loss = 0.20109048
Iteration 47, loss = 0.19816589
Iteration 48, loss = 0.19465288
Iteration 49, loss = 0.19066799
Iteration 50, loss = 0.18709352
Iteration 51, loss = 0.18399456
Iteration 52, loss = 0.18096035
Iteration 53, loss = 0.17824789
Iteration 54, loss = 0.17438131
Iteration 55, loss = 0.17104768
Iteration 56, loss = 0.16715642
Iteration 57, loss = 0.16419562
Iteration 58, loss = 0.16086274
Iteration 59, loss = 0.15689919
Iteration 60, loss = 0.15264138
Iteration 61, loss = 0.14934995
Iteration 62, loss = 0.14550277
Iteration 63, loss = 0.14291124
Iteration 64, loss = 0.14037061
Iteration 65, loss = 0.13681824
Iteration 66, loss = 0.13151398
Iteration 67, loss = 0.12808523
Iteration 68, loss = 0.12732438
Iteration 69, loss = 0.12331582
Iteration 70, loss = 0.11994672
Iteration 71, loss = 0.12144491
Iteration 72, loss = 0.11723312
Iteration 73, loss = 0.11014502
Iteration 74, loss = 0.10611942
Iteration 75, loss = 0.10419464
Iteration 76, loss = 0.10275828
Iteration 77, loss = 0.09982020
Iteration 78, loss = 0.09550642
Iteration 79, loss = 0.09212924
Iteration 80, loss = 0.08955126
Iteration 81, loss = 0.08818308
Iteration 82, loss = 0.08575067
Iteration 83, loss = 0.08180282
Iteration 84, loss = 0.08003110
Iteration 85, loss = 0.07934263
Iteration 86, loss = 0.07877177
Iteration 87, loss = 0.07697152
Iteration 88, loss = 0.07293530
Iteration 89, loss = 0.06973562
Iteration 90, loss = 0.06873299
Iteration 91, loss = 0.06717094
Iteration 92, loss = 0.06494310
Iteration 93, loss = 0.06259126
Iteration 94, loss = 0.06140926
Iteration 95, loss = 0.05948434
Iteration 96, loss = 0.05752480
Iteration 97, loss = 0.05943580
Iteration 98, loss = 0.06045753
Iteration 99, loss = 0.05640430
Iteration 100, loss = 0.05097122
Iteration 101, loss = 0.04809414
Iteration 102, loss = 0.04707809
Iteration 103, loss = 0.04911537
Iteration 104, loss = 0.05027883
Iteration 105, loss = 0.04692958
Iteration 106, loss = 0.04324588
Iteration 107, loss = 0.04269798
Iteration 108, loss = 0.04300703
Iteration 109, loss = 0.03984377
Iteration 110, loss = 0.03686173
Iteration 111, loss = 0.03885725
Iteration 112, loss = 0.04337721
Iteration 113, loss = 0.04226510
Iteration 114, loss = 0.03970377
Iteration 115, loss = 0.03650803
Iteration 116, loss = 0.03345121
Iteration 117, loss = 0.03562684
Iteration 118, loss = 0.03994271
Iteration 119, loss = 0.04076358
Iteration 120, loss = 0.03759157
Iteration 121, loss = 0.03471992
Iteration 122, loss = 0.03165116
Iteration 123, loss = 0.02881699
Iteration 124, loss = 0.02754822
Iteration 125, loss = 0.02846832
Iteration 126, loss = 0.02990263
Iteration 127, loss = 0.02780518
Iteration 128, loss = 0.02604527
Iteration 129, loss = 0.02593765
Iteration 130, loss = 0.02492969
Iteration 131, loss = 0.02284030
Iteration 132, loss = 0.02187765
Iteration 133, loss = 0.02203786
Iteration 134, loss = 0.02182147
Iteration 135, loss = 0.02135658
Iteration 136, loss = 0.02038401
Iteration 137, loss = 0.02103582
Iteration 138, loss = 0.02106359
Iteration 139, loss = 0.01947314
Iteration 140, loss = 0.01731181
Iteration 141, loss = 0.01762351
Iteration 142, loss = 0.01935545
Iteration 143, loss = 0.01797772
Iteration 144, loss = 0.01662302
Iteration 145, loss = 0.01822714
Iteration 146, loss = 0.02139024
Iteration 147, loss = 0.02137248
Iteration 148, loss = 0.01783615
Iteration 149, loss = 0.01506453
Iteration 150, loss = 0.01782876
Iteration 151, loss = 0.01693902
Iteration 152, loss = 0.01443021
Iteration 153, loss = 0.01401438
Iteration 154, loss = 0.01377652
Iteration 155, loss = 0.01311571
Iteration 156, loss = 0.01314523
Iteration 157, loss = 0.01258340
Iteration 158, loss = 0.01207314
Iteration 159, loss = 0.01181885
Iteration 160, loss = 0.01133943
Iteration 161, loss = 0.01080236
Iteration 162, loss = 0.01068506
Iteration 163, loss = 0.01047737
Iteration 164, loss = 0.01014661
Iteration 165, loss = 0.00971725
Iteration 166, loss = 0.00990952
Iteration 167, loss = 0.01043675
Iteration 168, loss = 0.01062045
Iteration 169, loss = 0.00967635
Iteration 170, loss = 0.00899467
Iteration 171, loss = 0.00888901
Iteration 172, loss = 0.00894910
Iteration 173, loss = 0.00899116
Iteration 174, loss = 0.00875652
Iteration 175, loss = 0.00814535
Iteration 176, loss = 0.00784402
Iteration 177, loss = 0.00783480
Iteration 178, loss = 0.00804668
Iteration 179, loss = 0.00770794
Iteration 180, loss = 0.00740957
Iteration 181, loss = 0.00765635
Iteration 182, loss = 0.00746716
Iteration 183, loss = 0.00707387
Iteration 184, loss = 0.00687460
Iteration 185, loss = 0.00681723
Iteration 186, loss = 0.00676029
Iteration 187, loss = 0.00658308
Iteration 188, loss = 0.00644517
Iteration 189, loss = 0.00644892
Iteration 190, loss = 0.00649082
Iteration 191, loss = 0.00635873
Iteration 192, loss = 0.00616858
Iteration 193, loss = 0.00607827
Iteration 194, loss = 0.00616651
Iteration 195, loss = 0.00622376
Iteration 196, loss = 0.00591538
Iteration 197, loss = 0.00559345
Iteration 198, loss = 0.00548787
Iteration 199, loss = 0.00542118
Iteration 200, loss = 0.00539678
Iteration 201, loss = 0.00552420
Iteration 202, loss = 0.00545524
Iteration 203, loss = 0.00526032
Iteration 204, loss = 0.00509812
Iteration 205, loss = 0.00505680
Iteration 206, loss = 0.00482049
Iteration 207, loss = 0.00470555
Iteration 208, loss = 0.00475318
Iteration 209, loss = 0.00505376
Iteration 210, loss = 0.00509477
Iteration 211, loss = 0.00482540
Iteration 212, loss = 0.00445447
Iteration 213, loss = 0.00431326
Iteration 214, loss = 0.00451102
Iteration 215, loss = 0.00466933
Iteration 216, loss = 0.00445787
Iteration 217, loss = 0.00411363
Iteration 218, loss = 0.00398251
Iteration 219, loss = 0.00393789
Iteration 220, loss = 0.00403203
Iteration 221, loss = 0.00404778
Iteration 222, loss = 0.00392521
Iteration 223, loss = 0.00372907
Iteration 224, loss = 0.00354584
Iteration 225, loss = 0.00351446
Iteration 226, loss = 0.00368953
Iteration 227, loss = 0.00390519
Iteration 228, loss = 0.00401787
Iteration 229, loss = 0.00397248
Iteration 230, loss = 0.00374076
Iteration 231, loss = 0.00345612
Iteration 232, loss = 0.00326583
Iteration 233, loss = 0.00322988
Iteration 234, loss = 0.00326705
Iteration 235, loss = 0.00332739
Iteration 236, loss = 0.00336246
Iteration 237, loss = 0.00328098
Iteration 238, loss = 0.00310415
Iteration 239, loss = 0.00292369
Iteration 240, loss = 0.00288241
Iteration 241, loss = 0.00294396
Iteration 242, loss = 0.00303971
Iteration 243, loss = 0.00314972
Iteration 244, loss = 0.00323383
Iteration 245, loss = 0.00307158
Iteration 246, loss = 0.00285329
Iteration 247, loss = 0.00269921
Iteration 248, loss = 0.00259498
Iteration 249, loss = 0.00252188
Iteration 250, loss = 0.00249778
Iteration 251, loss = 0.00251263
Iteration 252, loss = 0.00254764
Iteration 253, loss = 0.00253721
Iteration 254, loss = 0.00251910
Iteration 255, loss = 0.00242752
Iteration 256, loss = 0.00230989
Iteration 257, loss = 0.00232220
Iteration 258, loss = 0.00238152
Iteration 259, loss = 0.00244466
Iteration 260, loss = 0.00233503
Iteration 261, loss = 0.00227656
Iteration 262, loss = 0.00225650
Iteration 263, loss = 0.00221468
Iteration 264, loss = 0.00218561
Iteration 265, loss = 0.00216336
Iteration 266, loss = 0.00218180
Iteration 267, loss = 0.00206960
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.7768      0.709  0.7768  0.7042

## 9. Save results file

In [16]:
# results.to_csv(HOME_PATH+'RESULTS/models_results_ctgan.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.7768     0.6094  0.7768  0.6830
1   KNN    0.7811     0.6101  0.7811  0.6851
2    DT    0.6052     0.6402  0.6052  0.6211
3   SVM    0.5794     0.6790  0.5794  0.6133
4   MLP    0.7768     0.7090  0.7768  0.7042