# TSTR GM

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
HOME_PATH = 'C:/Users/27261/Desktop/prostate/code-0126/'
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(HOME_PATH + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
train_data = pd.read_csv(HOME_PATH + 'Dataset_cedric/SYNTHETIC DATASETS/GM.csv')
categorical_columns = ["cT(MRI)","Multifocaal", "pN", "1c (0) - Perifeer (1) -  Beide (2) - Transitie (3)"]
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,eadnr (I),Age,Multifocaal,1c (0) - Perifeer (1) - Beide (2) - Transitie (3),Preoperatief PSA,Aantal zones positive percentage,Primaire Gleason,Secundaire Gleason,Grade group (highest),Target biopsie Core length (perc),...,Grootste diameter (percentage of tumor),Grootste mm aantasting (mms),Primaire,Secundaire,Grade group Grootste mm aantasting,Primaire Gleason.1,Secundaire Gleason.1,Grade Group,pN,cT(MRI)
0,58909342,64.337688,0,3,9.982891,0.989633,3,4,3,96.205341,...,104.609400,15.885067,3,4,2,3,4,2,0,5
1,80189740,71.923308,0,1,5.495949,0.498560,2,4,2,52.777547,...,48.742101,5.011527,3,3,3,3,4,3,1,1
2,90202088,65.530081,0,1,8.555178,0.160064,4,5,4,61.047230,...,52.643005,7.407782,3,4,4,3,4,2,0,6
3,73384281,51.221856,1,2,27.552564,0.914531,3,2,2,31.757763,...,49.548227,8.706428,3,3,2,2,2,1,0,1
4,86167663,59.597295,1,2,7.167456,0.379130,2,2,2,73.010322,...,72.198774,10.362673,3,2,2,3,3,2,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,64239278,56.499214,0,1,10.612731,0.527268,3,4,3,53.629011,...,57.346745,11.250139,3,4,2,2,3,2,0,3
229,85461163,74.756860,1,2,10.495777,0.742370,3,3,2,64.249979,...,76.870440,8.674526,3,3,2,3,4,2,1,1
230,76405155,57.392086,1,2,6.814344,0.218064,5,2,5,-0.269323,...,16.917209,3.504668,4,3,4,3,3,2,0,4
231,63404885,66.365712,0,3,7.469369,0.108382,3,2,1,69.591380,...,60.017642,8.760353,3,2,1,2,4,1,0,4
232,91058007,66.828639,1,1,5.593988,0.499001,5,2,4,25.563359,...,30.898313,3.537649,5,3,4,4,4,4,0,4

In [4]:
#read test data
test_data = pd.read_csv(HOME_PATH + 'Dataset_cedric/SYNTHETIC DATASETS/GM-2.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,eadnr (I),Age,Multifocaal,1c (0) - Perifeer (1) - Beide (2) - Transitie (3),Preoperatief PSA,Aantal zones positive percentage,Primaire Gleason,Secundaire Gleason,Grade group (highest),Target biopsie Core length (perc),...,Grootste diameter (percentage of tumor),Grootste mm aantasting (mms),Primaire,Secundaire,Grade group Grootste mm aantasting,Primaire Gleason.1,Secundaire Gleason.1,Grade Group,pN,cT(MRI)
0,80751055,65.717895,0,1,22.797505,0.546302,3,3,3,101.459885,...,78.159285,10.747841,3,3,4,3,3,2,1,5
1,57898186,60.952653,0,3,11.819504,0.175692,3,3,2,23.170606,...,46.556948,12.647333,2,3,1,3,3,2,1,3
2,69382575,69.103902,0,3,7.760623,0.704903,4,3,4,43.048387,...,41.611721,10.396189,3,4,4,4,3,3,0,6
3,63193765,66.479520,0,1,6.481028,-0.035011,4,3,4,72.911951,...,74.447866,7.649607,4,3,3,4,3,4,1,3
4,59555950,56.989128,0,1,9.340347,0.488734,3,4,2,56.914958,...,55.548996,5.258657,2,4,2,3,4,2,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,88612935,64.076222,1,3,12.570309,0.443207,2,3,1,99.296709,...,84.190945,11.061089,2,3,1,2,3,1,0,1
229,76138880,69.271280,1,2,24.683309,0.372322,4,3,5,39.468390,...,75.823338,11.777975,3,3,3,3,3,2,1,4
230,61496924,56.959193,0,1,13.227572,0.194276,2,4,2,73.821418,...,67.861227,9.122619,3,4,2,3,4,3,0,1
231,61707368,57.672218,0,1,5.983022,1.113974,5,3,5,73.157021,...,68.632453,6.070126,4,3,5,3,4,3,0,4
232,84625032,60.914702,1,1,8.895903,0.388606,3,3,2,48.759557,...,67.859295,9.529546,3,3,2,3,3,3,0,1

In [5]:
target = 'pN'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(233, 35)
pN
0    209
1     24
dtype: int64
#####################################
Test data
(233, 35)
pN
0    188
1     45
dtype: int64

## 2. Pre-process training data

In [6]:
target = "pN"
categorical_columns = ["cT(MRI)","Multifocaal", "1c (0) - Perifeer (1) -  Beide (2) - Transitie (3)"]
numerical_columns = numerical_columns = train_data.select_dtypes(include=['int64']).columns.tolist()
categories = [np.array(range(7)), np.array(range(2)), np.array(range(4))]

data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((233, 33), (233,))

## 3. Preprocess test data

In [7]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((233, 33), (233,))

## 4. Create a dataset to save the results

In [8]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [9]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF    0.8026     0.6504  0.8026  0.7185

## 5. Train and Evaluate KNeighbors Classifier

In [10]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.8069      0.651  0.8069  0.7206

## 6. Train and evaluate Decision Tree Classifier

In [11]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall     f1
0    DT    0.7468     0.6767  0.7468  0.706

## 7. Train and evaluate Support Vector Machines Classifier

In [12]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM]

  model  accuracy  precision  recall      f1
0   SVM    0.6996     0.6715  0.6996  0.6847

## 8. Train and evaluate Multilayer Perceptron Classifier

In [13]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.74156760
Iteration 2, loss = 0.62684077
Iteration 3, loss = 0.53899131
Iteration 4, loss = 0.47036566
Iteration 5, loss = 0.41408293
Iteration 6, loss = 0.37123639
Iteration 7, loss = 0.34013325
Iteration 8, loss = 0.32009093
Iteration 9, loss = 0.30894259
Iteration 10, loss = 0.30249604
Iteration 11, loss = 0.29768329
Iteration 12, loss = 0.29349480
Iteration 13, loss = 0.28988992
Iteration 14, loss = 0.28590379
Iteration 15, loss = 0.28161028
Iteration 16, loss = 0.27671425
Iteration 17, loss = 0.27169135
Iteration 18, loss = 0.26585240
Iteration 19, loss = 0.26001972
Iteration 20, loss = 0.25428131
Iteration 21, loss = 0.24922958
Iteration 22, loss = 0.24471409
Iteration 23, loss = 0.23983995
Iteration 24, loss = 0.23588574
Iteration 25, loss = 0.23172157
Iteration 26, loss = 0.22675050
Iteration 27, loss = 0.22282920
Iteration 28, loss = 0.21799274
Iteration 29, loss = 0.21397616
Iteration 30, loss = 0.20996104
Iteration 31, loss = 0.20548212
Iteration 32, loss = 0.20046640
Iteration 33, loss = 0.19639466
Iteration 34, loss = 0.19155774
Iteration 35, loss = 0.18651448
Iteration 36, loss = 0.18152640
Iteration 37, loss = 0.17670875
Iteration 38, loss = 0.17207842
Iteration 39, loss = 0.16815447
Iteration 40, loss = 0.16404056
Iteration 41, loss = 0.16022822
Iteration 42, loss = 0.15580959
Iteration 43, loss = 0.15083393
Iteration 44, loss = 0.14514662
Iteration 45, loss = 0.14149323
Iteration 46, loss = 0.13791209
Iteration 47, loss = 0.13378945
Iteration 48, loss = 0.12871543
Iteration 49, loss = 0.12409284
Iteration 50, loss = 0.11990514
Iteration 51, loss = 0.11501464
Iteration 52, loss = 0.10999896
Iteration 53, loss = 0.10536211
Iteration 54, loss = 0.10163579
Iteration 55, loss = 0.09718026
Iteration 56, loss = 0.09298412
Iteration 57, loss = 0.08861493
Iteration 58, loss = 0.08467797
Iteration 59, loss = 0.08059079
Iteration 60, loss = 0.07664949
Iteration 61, loss = 0.07260305
Iteration 62, loss = 0.06878655
Iteration 63, loss = 0.06525567
Iteration 64, loss = 0.06177964
Iteration 65, loss = 0.05795529
Iteration 66, loss = 0.05442411
Iteration 67, loss = 0.05115936
Iteration 68, loss = 0.04817192
Iteration 69, loss = 0.04482621
Iteration 70, loss = 0.04186108
Iteration 71, loss = 0.03926080
Iteration 72, loss = 0.03641051
Iteration 73, loss = 0.03416556
Iteration 74, loss = 0.03198534
Iteration 75, loss = 0.02986763
Iteration 76, loss = 0.02787933
Iteration 77, loss = 0.02617701
Iteration 78, loss = 0.02452169
Iteration 79, loss = 0.02309645
Iteration 80, loss = 0.02142821
Iteration 81, loss = 0.02002314
Iteration 82, loss = 0.01915653
Iteration 83, loss = 0.01812117
Iteration 84, loss = 0.01692549
Iteration 85, loss = 0.01565864
Iteration 86, loss = 0.01446634
Iteration 87, loss = 0.01359883
Iteration 88, loss = 0.01296568
Iteration 89, loss = 0.01227982
Iteration 90, loss = 0.01149935
Iteration 91, loss = 0.01080312
Iteration 92, loss = 0.01018680
Iteration 93, loss = 0.00955837
Iteration 94, loss = 0.00906191
Iteration 95, loss = 0.00857513
Iteration 96, loss = 0.00809366
Iteration 97, loss = 0.00769297
Iteration 98, loss = 0.00736423
Iteration 99, loss = 0.00708191
Iteration 100, loss = 0.00675320
Iteration 101, loss = 0.00641335
Iteration 102, loss = 0.00613352
Iteration 103, loss = 0.00585173
Iteration 104, loss = 0.00558176
Iteration 105, loss = 0.00532199
Iteration 106, loss = 0.00507706
Iteration 107, loss = 0.00484650
Iteration 108, loss = 0.00465289
Iteration 109, loss = 0.00446552
Iteration 110, loss = 0.00427891
Iteration 111, loss = 0.00408767
Iteration 112, loss = 0.00388186
Iteration 113, loss = 0.00369705
Iteration 114, loss = 0.00354589
Iteration 115, loss = 0.00343172
Iteration 116, loss = 0.00331571
Iteration 117, loss = 0.00319369
Iteration 118, loss = 0.00303789
Iteration 119, loss = 0.00290033
Iteration 120, loss = 0.00279649
Iteration 121, loss = 0.00272307
Iteration 122, loss = 0.00264675
Iteration 123, loss = 0.00256447
Iteration 124, loss = 0.00248163
Iteration 125, loss = 0.00239742
Iteration 126, loss = 0.00232545
Iteration 127, loss = 0.00226913
Iteration 128, loss = 0.00220681
Iteration 129, loss = 0.00213556
Iteration 130, loss = 0.00206454
Iteration 131, loss = 0.00199919
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.8026      0.753  0.8026  0.7559

## 9. Save results file

In [14]:
# results.to_csv(HOME_PATH + 'RESULTS/models_results_gm.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.8026     0.6504  0.8026  0.7185
1   KNN    0.8069     0.6510  0.8069  0.7206
2    DT    0.7468     0.6767  0.7468  0.7060
3   SVM    0.6996     0.6715  0.6996  0.6847
4   MLP    0.8026     0.7530  0.8026  0.7559