# TSTR WGANGP

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
HOME_PATH = 'C:/Users/27261/Desktop/prostate/code-0126/'
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(HOME_PATH + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
#read real dataset
train_data = pd.read_csv(HOME_PATH + 'Dataset_cedric/SYNTHETIC DATASETS/WGANGP.csv')
categorical_columns = ["cT(MRI)","Multifocaal", "pN", "1c (0) - Perifeer (1) -  Beide (2) - Transitie (3)"]
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,eadnr (I),Age,Multifocaal,1c (0) - Perifeer (1) - Beide (2) - Transitie (3),Preoperatief PSA,Aantal zones positive percentage,Primaire Gleason,Secundaire Gleason,Grade group (highest),Target biopsie Core length (perc),...,Grootste diameter (percentage of tumor),Grootste mm aantasting (mms),Primaire,Secundaire,Grade group Grootste mm aantasting,Primaire Gleason.1,Secundaire Gleason.1,Grade Group,pN,cT(MRI)
0,67360704,55.632397,0,1,16.042311,-0.061713,3,3,2,50.874027,...,69.842308,3.186382,3,2,1,3,3,1,0,4
1,66874764,52.770901,0,1,19.027332,0.057281,3,2,2,47.970814,...,52.340023,1.464574,3,2,1,3,3,1,0,4
2,66687892,54.142345,0,1,20.480595,-0.009403,3,3,2,53.226791,...,51.009029,3.261557,3,2,1,3,3,1,0,4
3,69780672,58.598602,0,1,14.343013,-0.080210,3,3,2,61.369087,...,64.289185,2.490963,3,2,1,3,3,1,1,4
4,66684832,54.072430,0,1,5.600604,0.023530,3,2,2,47.753101,...,50.606117,1.494166,3,2,1,3,3,1,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,70849336,54.636955,0,1,10.592919,0.074774,3,2,2,62.640102,...,70.276543,2.687879,3,2,1,3,3,1,0,1
229,68792168,54.218044,0,1,-9.360442,0.061045,3,3,2,52.218075,...,53.375885,2.209548,3,2,1,3,3,1,0,1
230,69266968,57.274818,0,1,-0.832032,0.050229,3,2,2,62.431156,...,63.008644,3.394243,3,2,1,3,3,1,1,4
231,68060080,56.961246,0,1,4.401272,-0.060569,3,2,2,59.421577,...,58.368599,1.935508,3,2,1,3,3,1,0,4
232,70741688,56.654839,0,1,2.127598,-0.036717,3,3,2,63.332634,...,65.631523,1.548735,3,2,1,3,3,1,0,4

In [4]:
#read test data
test_data = pd.read_csv(HOME_PATH + 'Dataset_cedric/SYNTHETIC DATASETS/WGANGP-2.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,eadnr (I),Age,Multifocaal,1c (0) - Perifeer (1) - Beide (2) - Transitie (3),Preoperatief PSA,Aantal zones positive percentage,Primaire Gleason,Secundaire Gleason,Grade group (highest),Target biopsie Core length (perc),...,Grootste diameter (percentage of tumor),Grootste mm aantasting (mms),Primaire,Secundaire,Grade group Grootste mm aantasting,Primaire Gleason.1,Secundaire Gleason.1,Grade Group,pN,cT(MRI)
0,84676824,50.961609,1,2,46.835880,0.527339,4,2,3,60.061768,...,88.971870,4.173984,3,3,2,3,3,2,0,1
1,85140512,49.929680,1,2,61.010914,0.403266,4,3,3,66.329971,...,72.500710,2.864784,3,3,1,3,3,2,0,4
2,82776768,51.593681,1,2,74.331558,0.407112,4,3,3,65.345901,...,72.027702,3.719828,2,3,2,3,3,2,0,4
3,79681856,51.603085,1,2,48.577232,0.329649,4,2,3,55.110153,...,63.349052,4.366672,3,3,2,3,3,2,0,1
4,91650728,52.424927,1,2,71.156456,0.587035,4,2,3,72.364830,...,93.178192,5.079518,3,3,2,3,3,3,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,86623320,49.475887,1,2,77.816917,0.503106,4,3,4,74.210953,...,96.076668,6.584691,2,3,2,3,3,2,0,4
229,91095632,53.629219,1,2,62.161751,0.531124,4,3,3,77.162560,...,91.371986,4.476023,2,3,2,3,2,2,0,4
230,84774328,52.749996,1,2,45.923435,0.443878,4,3,3,76.847176,...,78.070107,4.614897,3,3,2,3,3,2,0,4
231,73967840,48.766918,1,2,53.256252,0.323729,3,3,2,34.650719,...,52.821392,2.717286,2,3,1,3,3,2,0,4
232,81500184,50.055408,1,2,63.542850,0.428498,4,3,3,62.004131,...,72.887428,4.143359,3,3,1,3,3,2,0,4

In [5]:
target = 'pN'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(233, 35)
pN
0    125
1    108
dtype: int64
#####################################
Test data
(233, 35)
pN
0    233
dtype: int64

## 2. Pre-process training data

In [6]:
target = "pN"
categorical_columns = ["cT(MRI)","Multifocaal", "1c (0) - Perifeer (1) -  Beide (2) - Transitie (3)"]
numerical_columns = numerical_columns = train_data.select_dtypes(include=['int64']).columns.tolist()
categories = [np.array(range(7)), np.array(range(2)), np.array(range(4))]

data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((233, 33), (233,))

## 3. Preprocess test data

In [7]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((233, 33), (233,))

## 4. Create a dataset to save the results

In [8]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [9]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF    0.1159        1.0  0.1159  0.2077

## 5. Train and Evaluate KNeighbors Classifier

In [10]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.9142        1.0  0.9142  0.9552

## 6. Train and evaluate Decision Tree Classifier

In [11]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.9528        1.0  0.9528  0.9758

## 7. Train and evaluate Support Vector Machines Classifier

In [12]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM]

  model  accuracy  precision  recall      f1
0   SVM    0.7725        1.0  0.7725  0.8717

## 8. Train and evaluate Multilayer Perceptron Classifier

In [13]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.67965270
Iteration 2, loss = 0.65953679
Iteration 3, loss = 0.64500349
Iteration 4, loss = 0.63405555
Iteration 5, loss = 0.62435972
Iteration 6, loss = 0.61538355
Iteration 7, loss = 0.60575120
Iteration 8, loss = 0.59853517
Iteration 9, loss = 0.58988357
Iteration 10, loss = 0.58239627
Iteration 11, loss = 0.57554753
Iteration 12, loss = 0.56954245
Iteration 13, loss = 0.56407100
Iteration 14, loss = 0.55902480
Iteration 15, loss = 0.55339330
Iteration 16, loss = 0.54610638
Iteration 17, loss = 0.53872467
Iteration 18, loss = 0.53406835
Iteration 19, loss = 0.52942382
Iteration 20, loss = 0.52525843
Iteration 21, loss = 0.52106623
Iteration 22, loss = 0.51635360
Iteration 23, loss = 0.51292902
Iteration 24, loss = 0.50937324
Iteration 25, loss = 0.50466381
Iteration 26, loss = 0.50045355
Iteration 27, loss = 0.49623000
Iteration 28, loss = 0.49278933
Iteration 29, loss = 0.48848755
Iteration 30, loss = 0.48405262
Iteration 31, loss = 0.48037962
Iteration 32, loss = 0.47638355
Iteration 33, loss = 0.47193514
Iteration 34, loss = 0.46744631
Iteration 35, loss = 0.46458176
Iteration 36, loss = 0.46227240
Iteration 37, loss = 0.45764654
Iteration 38, loss = 0.45259303
Iteration 39, loss = 0.44771515
Iteration 40, loss = 0.44373705
Iteration 41, loss = 0.44150061
Iteration 42, loss = 0.43964022
Iteration 43, loss = 0.43792441
Iteration 44, loss = 0.43514022
Iteration 45, loss = 0.43043231
Iteration 46, loss = 0.42606102
Iteration 47, loss = 0.42175679
Iteration 48, loss = 0.41770067
Iteration 49, loss = 0.41256936
Iteration 50, loss = 0.41059045
Iteration 51, loss = 0.40979743
Iteration 52, loss = 0.40576441
Iteration 53, loss = 0.39992675
Iteration 54, loss = 0.39500016
Iteration 55, loss = 0.39826855
Iteration 56, loss = 0.39898386
Iteration 57, loss = 0.39079766
Iteration 58, loss = 0.38304347
Iteration 59, loss = 0.38046357
Iteration 60, loss = 0.38196772
Iteration 61, loss = 0.37952455
Iteration 62, loss = 0.37517521
Iteration 63, loss = 0.36990940
Iteration 64, loss = 0.36716463
Iteration 65, loss = 0.36163217
Iteration 66, loss = 0.35731263
Iteration 67, loss = 0.35520091
Iteration 68, loss = 0.35194369
Iteration 69, loss = 0.34813403
Iteration 70, loss = 0.34690655
Iteration 71, loss = 0.34571975
Iteration 72, loss = 0.33874594
Iteration 73, loss = 0.34742635
Iteration 74, loss = 0.36694552
Iteration 75, loss = 0.35687850
Iteration 76, loss = 0.32933586
Iteration 77, loss = 0.34106901
Iteration 78, loss = 0.36172402
Iteration 79, loss = 0.34314232
Iteration 80, loss = 0.31818728
Iteration 81, loss = 0.32673625
Iteration 82, loss = 0.33613683
Iteration 83, loss = 0.32435946
Iteration 84, loss = 0.31418572
Iteration 85, loss = 0.31689622
Iteration 86, loss = 0.32933590
Iteration 87, loss = 0.32704053
Iteration 88, loss = 0.30852343
Iteration 89, loss = 0.29951399
Iteration 90, loss = 0.29949054
Iteration 91, loss = 0.29924195
Iteration 92, loss = 0.29505611
Iteration 93, loss = 0.28939007
Iteration 94, loss = 0.28443360
Iteration 95, loss = 0.28144893
Iteration 96, loss = 0.27842382

Iteration 97, loss = 0.27745692
Iteration 98, loss = 0.27281899
Iteration 99, loss = 0.26878198
Iteration 100, loss = 0.26503304
Iteration 101, loss = 0.26312605
Iteration 102, loss = 0.26069493
Iteration 103, loss = 0.26208704
Iteration 104, loss = 0.26209050
Iteration 105, loss = 0.25635313
Iteration 106, loss = 0.25267377
Iteration 107, loss = 0.24902386
Iteration 108, loss = 0.24712895
Iteration 109, loss = 0.24715434
Iteration 110, loss = 0.24494354
Iteration 111, loss = 0.24087831
Iteration 112, loss = 0.23886197
Iteration 113, loss = 0.23721337
Iteration 114, loss = 0.23372533
Iteration 115, loss = 0.23263275
Iteration 116, loss = 0.22874875
Iteration 117, loss = 0.22679658
Iteration 118, loss = 0.22906970
Iteration 119, loss = 0.22597081
Iteration 120, loss = 0.22428246
Iteration 121, loss = 0.22177360
Iteration 122, loss = 0.21820440
Iteration 123, loss = 0.21657429
Iteration 124, loss = 0.21304214
Iteration 125, loss = 0.21073469
Iteration 126, loss = 0.20835380
Iteration 127, loss = 0.20480620
Iteration 128, loss = 0.20227091
Iteration 129, loss = 0.20317002
Iteration 130, loss = 0.20007366
Iteration 131, loss = 0.20072746
Iteration 132, loss = 0.20426827
Iteration 133, loss = 0.19967353
Iteration 134, loss = 0.19280074
Iteration 135, loss = 0.19190987
Iteration 136, loss = 0.18917370
Iteration 137, loss = 0.19284492
Iteration 138, loss = 0.19178131
Iteration 139, loss = 0.18868518
Iteration 140, loss = 0.19559320
Iteration 141, loss = 0.19693428
Iteration 142, loss = 0.18337187
Iteration 143, loss = 0.17817410
Iteration 144, loss = 0.17636122
Iteration 145, loss = 0.17528618
Iteration 146, loss = 0.17413492
Iteration 147, loss = 0.17221505
Iteration 148, loss = 0.17657676
Iteration 149, loss = 0.17479366
Iteration 150, loss = 0.17163382
Iteration 151, loss = 0.16651546
Iteration 152, loss = 0.16362257
Iteration 153, loss = 0.16126494
Iteration 154, loss = 0.15986425
Iteration 155, loss = 0.15871457
Iteration 156, loss = 0.15719874
Iteration 157, loss = 0.15624165
Iteration 158, loss = 0.15552747
Iteration 159, loss = 0.15384999
Iteration 160, loss = 0.15512722
Iteration 161, loss = 0.15402664
Iteration 162, loss = 0.15374635
Iteration 163, loss = 0.15116488
Iteration 164, loss = 0.14824049
Iteration 165, loss = 0.14318963
Iteration 166, loss = 0.14590664
Iteration 167, loss = 0.14626370
Iteration 168, loss = 0.13944406
Iteration 169, loss = 0.14520315
Iteration 170, loss = 0.14997036
Iteration 171, loss = 0.13869071
Iteration 172, loss = 0.14427544
Iteration 173, loss = 0.14485702
Iteration 174, loss = 0.13417488
Iteration 175, loss = 0.13510529
Iteration 176, loss = 0.13811320
Iteration 177, loss = 0.14008888
Iteration 178, loss = 0.13702781
Iteration 179, loss = 0.13286625
Iteration 180, loss = 0.13173528
Iteration 181, loss = 0.12928841
Iteration 182, loss = 0.12905769
Iteration 183, loss = 0.13149175
Iteration 184, loss = 0.13559919
Iteration 185, loss = 0.13702535
Iteration 186, loss = 0.12350355
Iteration 187, loss = 0.13616724
Iteration 188, loss = 0.14572924
Iteration 189, loss = 0.12241568
Iteration 190, loss = 0.13252034
Iteration 191, loss = 0.12920838
Iteration 192, loss = 0.12270564
Iteration 193, loss = 0.13013258
Iteration 194, loss = 0.12626292
Iteration 195, loss = 0.11723641
Iteration 196, loss = 0.12681568
Iteration 197, loss = 0.15852438
Iteration 198, loss = 0.14952570
Iteration 199, loss = 0.12114423
Iteration 200, loss = 0.12123418
Iteration 201, loss = 0.11929221
Iteration 202, loss = 0.11936417
Iteration 203, loss = 0.12932677
Iteration 204, loss = 0.12120698
Iteration 205, loss = 0.11423232
Iteration 206, loss = 0.12375809
Iteration 207, loss = 0.12255158
Iteration 208, loss = 0.11839470
Iteration 209, loss = 0.11829955
Iteration 210, loss = 0.11528767
Iteration 211, loss = 0.11878473
Iteration 212, loss = 0.11827739
Iteration 213, loss = 0.10990164
Iteration 214, loss = 0.13359157
Iteration 215, loss = 0.11418218
Iteration 216, loss = 0.11295945
Iteration 217, loss = 0.13271879
Iteration 218, loss = 0.10843123
Iteration 219, loss = 0.10735930
Iteration 220, loss = 0.13196288
Iteration 221, loss = 0.12045619
Iteration 222, loss = 0.11736986
Iteration 223, loss = 0.13441511
Iteration 224, loss = 0.11691878
Iteration 225, loss = 0.10542660
Iteration 226, loss = 0.11740789
Iteration 227, loss = 0.11694475
Iteration 228, loss = 0.10439843
Iteration 229, loss = 0.10179694
Iteration 230, loss = 0.10518801
Iteration 231, loss = 0.10370858
Iteration 232, loss = 0.10238657
Iteration 233, loss = 0.10643236
Iteration 234, loss = 0.09738235
Iteration 235, loss = 0.09687724
Iteration 236, loss = 0.10528767
Iteration 237, loss = 0.10298314
Iteration 238, loss = 0.10436271
Iteration 239, loss = 0.10932977
Iteration 240, loss = 0.10831232
Iteration 241, loss = 0.09922146
Iteration 242, loss = 0.09030346
Iteration 243, loss = 0.09497142
Iteration 244, loss = 0.10769314
Iteration 245, loss = 0.10617971
Iteration 246, loss = 0.09991552
Iteration 247, loss = 0.09749789
Iteration 248, loss = 0.09542023
Iteration 249, loss = 0.09970199
Iteration 250, loss = 0.09756654
Iteration 251, loss = 0.09536525
Iteration 252, loss = 0.09340859
Iteration 253, loss = 0.09057907
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.0043        1.0  0.0043  0.0085

## 9. Save results file

In [14]:
# results.to_csv(HOME_PATH + 'RESULTS/models_results_wgangp.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.1159        1.0  0.1159  0.2077
1   KNN    0.9142        1.0  0.9142  0.9552
2    DT    0.9528        1.0  0.9528  0.9758
3   SVM    0.7725        1.0  0.7725  0.8717
4   MLP    0.0043        1.0  0.0043  0.0085