# TSTR WGANGP

In [1]:
#import libraries
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import os
print('Libraries imported!!')

Libraries imported!!

In [2]:
#define directory of functions and actual directory
HOME_PATH = 'C:/Users/27261/Desktop/prostate/code-0126/'
FUNCTIONS_DIR = 'EVALUATION FUNCTIONS/UTILITY'
ACTUAL_DIR = os.getcwd()

#change directory to functions directory
os.chdir(HOME_PATH + FUNCTIONS_DIR)

#import functions for data labelling analisys
from utility_evaluation import DataPreProcessor
from utility_evaluation import train_evaluate_model

#change directory to actual directory
os.chdir(ACTUAL_DIR)
print('Functions imported!!')

Functions imported!!

## 1. Read data

In [3]:
#read real dataset
train_data = pd.read_csv(HOME_PATH + 'Dataset_cedric/SYNTHETIC DATASETS/WGANGP.csv')
categorical_columns = ["cT(MRI)","Multifocaal", "pN", "1c (0) - Perifeer (1) -  Beide (2) - Transitie (3)"]
for col in categorical_columns :
    train_data[col] = train_data[col].astype('category')
train_data

,eadnr (I),Age,Multifocaal,1c (0) - Perifeer (1) - Beide (2) - Transitie (3),Preoperatief PSA,Aantal zones positive percentage,Primaire Gleason,Secundaire Gleason,Grade group (highest),Target biopsie Core length (perc),...,Grootste diameter (percentage of tumor),Grootste mm aantasting (mms),Primaire,Secundaire,Grade group Grootste mm aantasting,Primaire Gleason.1,Secundaire Gleason.1,Grade Group,pN,cT(MRI)
0,67360704,55.632397,0,1,16.042311,-0.061713,3,3,2,50.874027,...,69.842308,3.186382,3,2,1,3,3,1,0,4
1,66874764,52.770901,0,1,19.027332,0.057281,3,2,2,47.970814,...,52.340023,1.464574,3,2,1,3,3,1,0,4
2,66687892,54.142345,0,1,20.480595,-0.009403,3,3,2,53.226791,...,51.009029,3.261557,3,2,1,3,3,1,0,4
3,69780672,58.598602,0,1,14.343013,-0.080210,3,3,2,61.369087,...,64.289185,2.490963,3,2,1,3,3,1,1,4
4,66684832,54.072430,0,1,5.600604,0.023530,3,2,2,47.753101,...,50.606117,1.494166,3,2,1,3,3,1,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
228,70849336,54.636955,0,1,10.592919,0.074774,3,2,2,62.640102,...,70.276543,2.687879,3,2,1,3,3,1,0,1
229,68792168,54.218044,0,1,-9.360442,0.061045,3,3,2,52.218075,...,53.375885,2.209548,3,2,1,3,3,1,0,1
230,69266968,57.274818,0,1,-0.832032,0.050229,3,2,2,62.431156,...,63.008644,3.394243,3,2,1,3,3,1,1,4
231,68060080,56.961246,0,1,4.401272,-0.060569,3,2,2,59.421577,...,58.368599,1.935508,3,2,1,3,3,1,0,4
232,70741688,56.654839,0,1,2.127598,-0.036717,3,3,2,63.332634,...,65.631523,1.548735,3,2,1,3,3,1,0,4

In [4]:
#read test data
test_data = pd.read_csv(HOME_PATH + 'Dataset_cedric/Test.csv')
for col in categorical_columns :
    test_data[col] = test_data[col].astype('category')
test_data

,eadnr (I),Age,Multifocaal,1c (0) - Perifeer (1) - Beide (2) - Transitie (3),Preoperatief PSA,Aantal zones positive percentage,Primaire Gleason,Secundaire Gleason,Grade group (highest),Target biopsie Core length (perc),...,Grootste diameter (percentage of tumor),Grootste mm aantasting (mms),Primaire,Secundaire,Grade group Grootste mm aantasting,Primaire Gleason.1,Secundaire Gleason.1,Grade Group,pN,cT(MRI)
0,62001342,65.693151,0,1,5.84,1.000000,3,4,2,75.00,...,75.00,9.0,3,4,2,3,4,2,0,4
1,63137022,70.912329,0,1,22.00,0.444444,4,5,5,58.30,...,58.30,7.0,4,5,5,4,4,4,0,1
2,77465672,70.909589,1,1,6.20,1.000000,4,3,3,67.00,...,67.00,6.0,4,3,3,4,3,3,0,4
3,81146516,48.690411,0,1,5.13,0.818182,4,5,5,25.00,...,36.00,5.0,4,3,3,4,3,3,0,4
4,86707809,63.720548,1,2,3.60,0.363636,4,3,3,30.00,...,100.00,13.0,3,4,2,3,5,4,0,4
5,87588620,57.035616,0,3,5.87,0.200000,4,4,4,31.00,...,62.50,5.0,3,5,4,3,4,2,0,6
6,72672900,55.487671,1,3,5.81,0.200000,3,4,2,20.00,...,20.00,3.0,3,4,2,3,4,2,0,1
7,88047550,68.380822,1,1,5.20,0.200000,4,3,3,52.00,...,52.00,7.5,4,3,3,4,3,3,0,6
8,87903555,67.739726,0,1,6.06,1.000000,3,5,4,71.00,...,71.00,10.0,3,5,4,3,4,2,0,4
9,60961401,67.701370,0,3,18.59,0.333333,4,3,3,7.70,...,7.70,1.0,4,3,3,3,4,2,0,3
10,84927706,56.035616,0,1,8.00,0.272727,3,4,2,58.00,...,58.00,7.0,3,4,2,3,4,2,0,1
11,61020206,62.238356,0,1,13.60,0.272727,4,3,3,76.92,...,76.92,10.0,4,3,3,4,3,3,0,4
12,80532807,65.879452,0,1,5.07,1.000000,3,4,2,64.00,...,64.00,7.0,3,4,2,3,4,2,0,4
13,60694005,66.276712,0,1,8.41,0.750000,3,4,2,79.00,...,79.00,11.0,3,4,2,3,4,2,0,3
14,73471864,69.890411,1,3,20.65,0.083333,3,4,2,18.10,...,18.10,2.0,3,4,2,3,4,2,0,1
15,62981835,64.583562,1,2,0.43,1.000000,4,3,3,75.00,...,75.00,9.0,4,3,3,4,5,5,0,4
16,77406999,63.232877,1,2,6.66,1.000000,4,3,3,100.00,...,100.00,10.0,4,3,3,3,4,2,0,1
17,88382668,67.909589,0,1,2.69,1.000000,4,5,5,100.00,...,100.00,14.0,4,5,5,4,5,5,1,4
18,72131774,67.054795,0,3,4.72,0.400000,3,4,2,60.00,...,60.00,6.0,3,4,2,3,4,2,0,1
19,70356175,64.964384,1,2,11.00,0.600000,3,4,2,8.00,...,33.00,4.0,3,3,1,3,3,1,0,1
20,87594099,57.778082,1,2,5.37,0.909091,3,3,1,64.00,...,64.00,7.0,3,3,1,3,4,2,0,4
21,71433908,70.101370,0,3,22.66,0.714286,3,4,2,38.00,...,38.00,5.0,3,4,2,3,4,2,0,1
22,60751348,62.265753,0,1,9.47,0.500000,3,4,2,92.00,...,92.00,11.0,3,4,2,3,4,2,0,4
23,89916548,67.320548,0,1,10.00,1.000000,3,4,2,80.00,...,100.00,20.0,3,3,1,4,3,3,0,4
24,63389647,66.961644,0,1,10.39,1.000000,4,3,3,95.00,...,95.00,12.0,4,3,3,4,3,3,1,5
25,61072391,65.608219,0,3,6.00,0.181818,4,3,3,75.00,...,75.00,6.0,4,3,3,3,4,2,0,1
26,61026803,71.556164,0,0,7.72,0.200000,4,4,4,19.00,...,19.00,1.5,4,4,4,3,4,2,0,0
27,88460498,74.712329,0,1,5.99,0.727273,4,5,5,70.50,...,70.50,12.0,4,5,5,4,5,5,0,6
28,73900912,58.761644,0,1,14.40,1.000000,4,5,5,14.00,...,100.00,14.0,4,4,4,3,5,4,0,4
29,76087477,63.791781,0,3,8.62,0.500000,3,4,2,25.00,...,50.00,6.0,3,4,2,3,4,2,0,1
30,77914927,67.367123,1,2,6.76,1.000000,4,4,4,100.00,...,100.00,12.0,4,4,4,4,4,4,0,4
31,75089771,66.126027,0,1,18.60,1.000000,3,4,2,79.00,...,79.00,11.0,3,4,2,4,3,3,0,4
32,60497935,67.282192,1,2,4.98,0.200000,4,3,3,63.00,...,63.00,7.0,4,3,3,4,3,3,1,1
33,88053558,66.926027,1,1,3.90,0.500000,4,5,5,100.00,...,100.00,11.0,4,5,5,4,3,3,0,4
34,73986390,60.246575,0,3,21.00,1.000000,3,4,2,100.00,...,100.00,7.0,3,4,2,4,3,3,0,1
35,82304973,71.912329,1,2,10.00,0.454545,4,3,3,85.00,...,85.00,12.0,4,3,3,4,3,3,0,4
36,60634667,60.539726,0,3,7.33,0.400000,4,5,5,12.50,...,50.00,6.0,3,4,2,4,3,3,0,1
37,88309513,76.824658,1,1,10.44,0.200000,4,4,4,8.00,...,50.00,6.0,3,3,1,4,4,4,0,1
38,83004606,75.583562,0,1,5.59,0.700000,4,4,4,62.00,...,62.00,8.0,4,4,4,4,4,4,0,4
39,73573362,72.758904,0,3,10.90,1.000000,3,3,1,81.80,...,81.80,9.0,3,3,1,3,4,2,0,6
40,85075596,71.293151,0,1,26.70,0.750000,3,4,1,100.00,...,100.00,5.0,3,4,2,4,4,4,0,5
41,72967292,73.230137,1,3,18.03,0.750000,3,4,2,33.00,...,80.00,8.0,3,3,1,3,3,1,0,3
42,61347297,47.106849,1,1,5.68,0.300000,3,4,2,54.00,...,54.00,6.0,3,4,2,4,3,3,0,1
43,83070508,53.131507,0,1,11.40,0.600000,3,4,2,100.00,...,100.00,10.0,3,4,2,3,4,2,0,1
44,80082704,62.224658,0,3,28.00,0.272727,4,4,4,12.50,...,67.00,12.0,3,4,2,4,4,4,0,1
45,81287906,68.484932,0,1,10.29,1.000000,3,3,1,55.00,...,55.00,6.0,3,3,1,3,4,2,0,4
46,85031805,73.808219,0,1,13.88,0.500000,3,4,2,71.00,...,71.00,5.0,3,4,2,3,4,2,0,4
47,84215102,70.189041,0,1,6.50,1.000000,3,4,2,81.00,...,81.00,9.0,3,4,2,4,3,3,0,4
48,60918187,71.350685,0,1,12.00,0.545455,4,4,4,54.00,...,54.00,7.0,4,4,4,4,3,3,1,1
49,88040944,70.515068,1,2,3.20,0.100000,5,4,5,20.00,...,20.00,1.0,5,4,5,4,3,3,0,4
50,70060512,62.219178,1,2,7.80,0.300000,3,4,2,67.00,...,67.00,10.0,3,4,2,4,3,3,0,4
51,62914361,56.019178,0,1,3.70,0.600000,4,3,3,41.00,...,41.00,5.0,4,3,3,4,3,3,0,1
52,86469707,70.301370,0,1,11.30,1.000000,4,4,4,100.00,...,100.00,8.0,4,4,4,5,4,5,1,4
53,81534505,57.953425,1,2,4.20,1.000000,4,3,3,93.00,...,93.00,13.0,4,3,3,4,3,3,1,5
54,74631391,66.504110,0,1,7.73,0.200000,4,5,5,62.00,...,62.00,8.0,4,5,5,4,4,4,0,4
55,81010688,63.375342,0,1,2.49,0.500000,3,4,2,72.00,...,72.00,8.0,3,4,2,3,4,2,0,4
56,78519204,73.287671,1,2,8.61,0.200000,4,4,4,100.00,...,100.00,11.0,4,4,4,4,4,4,1,4
57,81947780,67.186301,1,1,4.50,0.300000,4,5,5,33.00,...,81.80,9.0,4,4,4,4,4,4,0,1
58,88216239,54.600000,1,2,4.30,0.250000,3,4,2,30.00,...,30.00,3.0,3,4,2,3,4,2,0,1

In [5]:
target = 'pN'
#quick look at the breakdown of class values
print('Train data')
print(train_data.shape)
print(train_data.groupby(target).size())
print('#####################################')
print('Test data')
print(test_data.shape)
print(test_data.groupby(target).size())

Train data
(233, 35)
pN
0    125
1    108
dtype: int64
#####################################
Test data
(59, 35)
pN
0    52
1     7
dtype: int64

## 2. Pre-process training data

In [6]:
target = "pN"
categorical_columns = ["cT(MRI)","Multifocaal", "1c (0) - Perifeer (1) -  Beide (2) - Transitie (3)"]
numerical_columns = numerical_columns = train_data.select_dtypes(include=['int64']).columns.tolist()
categories = [np.array(range(7)), np.array(range(2)), np.array(range(4))]

data_preprocessor = DataPreProcessor(categorical_columns, numerical_columns, categories)
x_train = data_preprocessor.preprocess_train_data(train_data.loc[:, train_data.columns != target])
y_train = train_data.loc[:, target]

x_train.shape, y_train.shape

((233, 33), (233,))

## 3. Preprocess test data

In [7]:
x_test = data_preprocessor.preprocess_test_data(test_data.loc[:, test_data.columns != target])
y_test = test_data.loc[:, target]
x_test.shape, y_test.shape

((59, 33), (59,))

## 4. Create a dataset to save the results

In [8]:
results = pd.DataFrame(columns = ['model','accuracy','precision','recall','f1'])
results

Empty DataFrame
Columns: [model, accuracy, precision, recall, f1]
Index: []

## 4. Train and evaluate Random Forest Classifier

In [9]:
rf_results = train_evaluate_model('RF', x_train, y_train, x_test, y_test)
results = pd.concat([results, rf_results], ignore_index=True)
rf_results

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.1s finished
[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  44 tasks      | elapsed:    0.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    0.0s finished

  model  accuracy  precision  recall      f1
0    RF     0.322      0.899   0.322  0.3613

## 5. Train and Evaluate KNeighbors Classifier

In [10]:
knn_results = train_evaluate_model('KNN', x_train, y_train, x_test, y_test)
results = pd.concat([results, knn_results], ignore_index=True)
knn_results

  model  accuracy  precision  recall      f1
0   KNN    0.5424     0.9058  0.5424  0.6128

## 6. Train and evaluate Decision Tree Classifier

In [11]:
dt_results = train_evaluate_model('DT', x_train, y_train, x_test, y_test)
results = pd.concat([results, dt_results], ignore_index=True)
dt_results

  model  accuracy  precision  recall      f1
0    DT    0.8814     0.7768  0.8814  0.8258

## 7. Train and evaluate Support Vector Machines Classifier

In [12]:
svm_results = train_evaluate_model('SVM', x_train, y_train, x_test, y_test)
results = pd.concat([results, svm_results], ignore_index=True)
svm_results

[LibSVM]

  model  accuracy  precision  recall      f1
0   SVM    0.2542     0.8976  0.2542  0.2637

## 8. Train and evaluate Multilayer Perceptron Classifier

In [13]:
mlp_results = train_evaluate_model('MLP', x_train, y_train, x_test, y_test)
results = pd.concat([results, mlp_results], ignore_index=True)
mlp_results

Iteration 1, loss = 0.67965270
Iteration 2, loss = 0.65953679
Iteration 3, loss = 0.64500349
Iteration 4, loss = 0.63405555
Iteration 5, loss = 0.62435972
Iteration 6, loss = 0.61538355
Iteration 7, loss = 0.60575120
Iteration 8, loss = 0.59853517
Iteration 9, loss = 0.58988357
Iteration 10, loss = 0.58239627
Iteration 11, loss = 0.57554753
Iteration 12, loss = 0.56954245
Iteration 13, loss = 0.56407100
Iteration 14, loss = 0.55902480
Iteration 15, loss = 0.55339330
Iteration 16, loss = 0.54610638
Iteration 17, loss = 0.53872467
Iteration 18, loss = 0.53406835
Iteration 19, loss = 0.52942382
Iteration 20, loss = 0.52525843
Iteration 21, loss = 0.52106623
Iteration 22, loss = 0.51635360
Iteration 23, loss = 0.51292902
Iteration 24, loss = 0.50937324
Iteration 25, loss = 0.50466381
Iteration 26, loss = 0.50045355
Iteration 27, loss = 0.49623000
Iteration 28, loss = 0.49278933
Iteration 29, loss = 0.48848755
Iteration 30, loss = 0.48405262
Iteration 31, loss = 0.48037962
Iteration 32, loss = 0.47638355
Iteration 33, loss = 0.47193514
Iteration 34, loss = 0.46744631
Iteration 35, loss = 0.46458176
Iteration 36, loss = 0.46227240
Iteration 37, loss = 0.45764654
Iteration 38, loss = 0.45259303
Iteration 39, loss = 0.44771515
Iteration 40, loss = 0.44373705
Iteration 41, loss = 0.44150061
Iteration 42, loss = 0.43964022
Iteration 43, loss = 0.43792441
Iteration 44, loss = 0.43514022
Iteration 45, loss = 0.43043231
Iteration 46, loss = 0.42606102
Iteration 47, loss = 0.42175679
Iteration 48, loss = 0.41770067
Iteration 49, loss = 0.41256936
Iteration 50, loss = 0.41059045
Iteration 51, loss = 0.40979743
Iteration 52, loss = 0.40576441
Iteration 53, loss = 0.39992675
Iteration 54, loss = 0.39500016
Iteration 55, loss = 0.39826855
Iteration 56, loss = 0.39898386
Iteration 57, loss = 0.39079766
Iteration 58, loss = 0.38304347
Iteration 59, loss = 0.38046357
Iteration 60, loss = 0.38196772
Iteration 61, loss = 0.37952455
Iteration 62, loss = 0.37517521
Iteration 63, loss = 0.36990940
Iteration 64, loss = 0.36716463
Iteration 65, loss = 0.36163217
Iteration 66, loss = 0.35731263
Iteration 67, loss = 0.35520091
Iteration 68, loss = 0.35194369
Iteration 69, loss = 0.34813403
Iteration 70, loss = 0.34690655
Iteration 71, loss = 0.34571975
Iteration 72, loss = 0.33874594
Iteration 73, loss = 0.34742635
Iteration 74, loss = 0.36694552
Iteration 75, loss = 0.35687850
Iteration 76, loss = 0.32933586
Iteration 77, loss = 0.34106901
Iteration 78, loss = 0.36172402
Iteration 79, loss = 0.34314232
Iteration 80, loss = 0.31818728
Iteration 81, loss = 0.32673625
Iteration 82, loss = 0.33613683
Iteration 83, loss = 0.32435946
Iteration 84, loss = 0.31418572
Iteration 85, loss = 0.31689622
Iteration 86, loss = 0.32933590
Iteration 87, loss = 0.32704053
Iteration 88, loss = 0.30852343
Iteration 89, loss = 0.29951399
Iteration 90, loss = 0.29949054
Iteration 91, loss = 0.29924195
Iteration 92, loss = 0.29505611
Iteration 93, loss = 0.28939007
Iteration 94, loss = 0.28443360
Iteration 95, loss = 0.28144893
Iteration 96, loss = 0.27842382
Iteration 97, loss = 0.27745692
Iteration 98, loss = 0.27281899
Iteration 99, loss = 0.26878198
Iteration 100, loss = 0.26503304
Iteration 101, loss = 0.26312605
Iteration 102, loss = 0.26069493
Iteration 103, loss = 0.26208704
Iteration 104, loss = 0.26209050
Iteration 105, loss = 0.25635313
Iteration 106, loss = 0.25267377
Iteration 107, loss = 0.24902386
Iteration 108, loss = 0.24712895
Iteration 109, loss = 0.24715434
Iteration 110, loss = 0.24494354
Iteration 111, loss = 0.24087831
Iteration 112, loss = 0.23886197
Iteration 113, loss = 0.23721337
Iteration 114, loss = 0.23372533
Iteration 115, loss = 0.23263275
Iteration 116, loss = 0.22874875
Iteration 117, loss = 0.22679658
Iteration 118, loss = 0.22906970
Iteration 119, loss = 0.22597081
Iteration 120, loss = 0.22428246
Iteration 121, loss = 0.22177360
Iteration 122, loss = 0.21820440
Iteration 123, loss = 0.21657429
Iteration 124, loss = 0.21304214
Iteration 125, loss = 0.21073469
Iteration 126, loss = 0.20835380
Iteration 127, loss = 0.20480620
Iteration 128, loss = 0.20227091
Iteration 129, loss = 0.20317002
Iteration 130, loss = 0.20007366
Iteration 131, loss = 0.20072746
Iteration 132, loss = 0.20426827
Iteration 133, loss = 0.19967353
Iteration 134, loss = 0.19280074
Iteration 135, loss = 0.19190987
Iteration 136, loss = 0.18917370
Iteration 137, loss = 0.19284492
Iteration 138, loss = 0.19178131
Iteration 139, loss = 0.18868518
Iteration 140, loss = 0.19559320
Iteration 141, loss = 0.19693428
Iteration 142, loss = 0.18337187
Iteration 143, loss = 0.17817410
Iteration 144, loss = 0.17636122
Iteration 145, loss = 0.17528618
Iteration 146, loss = 0.17413492
Iteration 147, loss = 0.17221505
Iteration 148, loss = 0.17657676
Iteration 149, loss = 0.17479366
Iteration 150, loss = 0.17163382
Iteration 151, loss = 0.16651546
Iteration 152, loss = 0.16362257
Iteration 153, loss = 0.16126494
Iteration 154, loss = 0.15986425
Iteration 155, loss = 0.15871457
Iteration 156, loss = 0.15719874
Iteration 157, loss = 0.15624165
Iteration 158, loss = 0.15552747
Iteration 159, loss = 0.15384999
Iteration 160, loss = 0.15512722
Iteration 161, loss = 0.15402664
Iteration 162, loss = 0.15374635
Iteration 163, loss = 0.15116488
Iteration 164, loss = 0.14824049
Iteration 165, loss = 0.14318963
Iteration 166, loss = 0.14590664
Iteration 167, loss = 0.14626370
Iteration 168, loss = 0.13944406
Iteration 169, loss = 0.14520315
Iteration 170, loss = 0.14997036
Iteration 171, loss = 0.13869071
Iteration 172, loss = 0.14427544
Iteration 173, loss = 0.14485702
Iteration 174, loss = 0.13417488
Iteration 175, loss = 0.13510529
Iteration 176, loss = 0.13811320
Iteration 177, loss = 0.14008888
Iteration 178, loss = 0.13702781
Iteration 179, loss = 0.13286625
Iteration 180, loss = 0.13173528
Iteration 181, loss = 0.12928841
Iteration 182, loss = 0.12905769
Iteration 183, loss = 0.13149175
Iteration 184, loss = 0.13559919
Iteration 185, loss = 0.13702535
Iteration 186, loss = 0.12350355
Iteration 187, loss = 0.13616724
Iteration 188, loss = 0.14572924
Iteration 189, loss = 0.12241568
Iteration 190, loss = 0.13252034
Iteration 191, loss = 0.12920838
Iteration 192, loss = 0.12270564
Iteration 193, loss = 0.13013258
Iteration 194, loss = 0.12626292
Iteration 195, loss = 0.11723641
Iteration 196, loss = 0.12681568
Iteration 197, loss = 0.15852438
Iteration 198, loss = 0.14952570
Iteration 199, loss = 0.12114423
Iteration 200, loss = 0.12123418
Iteration 201, loss = 0.11929221
Iteration 202, loss = 0.11936417
Iteration 203, loss = 0.12932677
Iteration 204, loss = 0.12120698
Iteration 205, loss = 0.11423232
Iteration 206, loss = 0.12375809
Iteration 207, loss = 0.12255158
Iteration 208, loss = 0.11839470
Iteration 209, loss = 0.11829955
Iteration 210, loss = 0.11528767
Iteration 211, loss = 0.11878473
Iteration 212, loss = 0.11827739
Iteration 213, loss = 0.10990164
Iteration 214, loss = 0.13359157
Iteration 215, loss = 0.11418218
Iteration 216, loss = 0.11295945
Iteration 217, loss = 0.13271879
Iteration 218, loss = 0.10843123
Iteration 219, loss = 0.10735930
Iteration 220, loss = 0.13196288
Iteration 221, loss = 0.12045619
Iteration 222, loss = 0.11736986
Iteration 223, loss = 0.13441511
Iteration 224, loss = 0.11691878
Iteration 225, loss = 0.10542660
Iteration 226, loss = 0.11740789
Iteration 227, loss = 0.11694475
Iteration 228, loss = 0.10439843
Iteration 229, loss = 0.10179694
Iteration 230, loss = 0.10518801
Iteration 231, loss = 0.10370858
Iteration 232, loss = 0.10238657
Iteration 233, loss = 0.10643236
Iteration 234, loss = 0.09738235
Iteration 235, loss = 0.09687724
Iteration 236, loss = 0.10528767
Iteration 237, loss = 0.10298314
Iteration 238, loss = 0.10436271
Iteration 239, loss = 0.10932977
Iteration 240, loss = 0.10831232
Iteration 241, loss = 0.09922146
Iteration 242, loss = 0.09030346
Iteration 243, loss = 0.09497142
Iteration 244, loss = 0.10769314
Iteration 245, loss = 0.10617971
Iteration 246, loss = 0.09991552
Iteration 247, loss = 0.09749789
Iteration 248, loss = 0.09542023
Iteration 249, loss = 0.09970199
Iteration 250, loss = 0.09756654
Iteration 251, loss = 0.09536525
Iteration 252, loss = 0.09340859
Iteration 253, loss = 0.09057907
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

  model  accuracy  precision  recall      f1
0   MLP    0.1864     0.8965  0.1864  0.1527

## 9. Save results file

In [14]:
results.to_csv(HOME_PATH + 'RESULTS/models_results_wgangp.csv', index=False)
results

  model  accuracy  precision  recall      f1
0    RF    0.3220     0.8990  0.3220  0.3613
1   KNN    0.5424     0.9058  0.5424  0.6128
2    DT    0.8814     0.7768  0.8814  0.8258
3   SVM    0.2542     0.8976  0.2542  0.2637
4   MLP    0.1864     0.8965  0.1864  0.1527